_extends: .github
repository:
  name: lint-my-app
  description: So you can write your app instead of lint it!
  homepage: https://saiichihashimoto.github.io/lint-my-app/
  topics: check, code, eslint, fix, fixjson, format, imagemin, lint, lint-staged, optimize, quality, sort, staged, stylelint, validate
branches:
  - name: master
    protection:
      required_status_checks:
        contexts: ['Semantic Pull Request', 'continuous-integration/travis-ci', 'coverage/coveralls']
